In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()
list(iris.keys())
X = iris["data"][:, 3:]
y = (iris["target"] == 2).astype(np.int)

from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(solver='lbfgs')
log_reg.fit(X, y)

X_new = np.linspace(0, 3, 1000).reshape(-1, 1)
y_proba = log_reg.predict_proba(X_new)
plt.plot(X_new, y_proba[:, 1], "g-", label="Iris-Virginica")
plt.plot(X_new, y_proba[:, 0], "b--", label="Iris-Virginica 아님")

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "C:\Users\ICT01_04\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-e3715b89c20e>", line 4, in <module>
    from sklearn import datasets
  File "C:\Users\ICT01_04\Anaconda3\lib\site-packages\sklearn\datasets\__init__.py", line 22, in <module>
    from ._twenty_newsgroups import fetch_20newsgroups
  File "C:\Users\ICT01_04\Anaconda3\lib\site-packages\sklearn\datasets\_twenty_newsgroups.py", line 45, in <module>
    from ..feature_extraction.text import CountVectorizer
  File "C:\Users\ICT01_04\Anaconda3\lib\site-packages\sklearn\feature_extraction\__init__.py", line 10, in <module>
    from . import text
  File "C:\Users\ICT01_04\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py", line 29, in <module>
    from ..preprocessing import normalize
  File "C:\Users\ICT01_04\Anaconda3\lib\site-packages\sklearn\preprocessing\

ImportError: cannot import name '_allclose_dense_sparse' from 'sklearn.utils.validation' (C:\Users\ICT01_04\Anaconda3\lib\site-packages\sklearn\utils\validation.py)

In [4]:
log_reg.predict([[1.7], [1.5]])

array([1, 0])

In [7]:
X = iris["data"][:, (2, 3)]
y = iris["target"]
softmax_reg = LogisticRegression(multi_class="multinomial", solver="lbfgs", C= 10)
softmax_reg.fit(X,y)

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
softmax_reg.predict([[5,2]])
softmax_reg.predict_proba([[5,2]])

array([[6.38014896e-07, 5.74929995e-02, 9.42506362e-01]])

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

pd.set_option('display.max_columns', None)
pr=pd.read_csv('prep 합친거.csv')
pr

Unnamed: 0  year  std_total  std_exp  hiv  smoke  drink  stress  depress  \
0            0  2000        NaN      NaN    2    NaN    NaN     NaN      NaN   
1            1  2001        NaN      NaN    6    NaN    NaN     NaN      NaN   
2            2  2002      0.028      NaN    5    NaN    NaN     NaN      NaN   
3            3  2003      0.021      NaN    6    NaN    NaN     NaN      NaN   
4            4  2004      0.014      NaN   12    NaN    NaN     NaN      NaN   
5            5  2005      0.009      NaN   16    NaN    NaN     NaN      NaN   
6            6  2006      0.006     0.13   13   12.8   28.6    46.5     41.4   
7            7  2007      0.006     0.12   17   13.3   27.8    46.5     41.3   
8            8  2008      0.006     0.11   20   12.8   24.5    43.7     38.8   
9            9  2009      0.005     0.10   27   12.8   21.1    43.2     37.5   
10          10  2010      0.005     0.09   28   12.1   21.1    43.8     37.4   
11          11  2011      0.006     0.11   40   12.1   20.6    42.0     32.8   
12          12  2012      0.006     0.13   32   11.4   19.4    41.9     30.5   
13          13  2013      0.006     0.11   53    9.7   16.3    41.4     30.9   
14          14  2014      0.007     0.13   40    9.2   16.7    37.0     26.7   
15          15  2015      0.013     0.26   42    7.8   16.7    35.4     23.6   
16          16  2016      0.018     0.39   36    6.3   15.0    37.4     25.5   
17          17  2017      0.018     0.35   34    6.4   16.1    37.2     25.1   
18          18  2018      0.026     0.46   19    6.7   16.9    40.4     27.1   

    sex_frequency  contraception  abortion  obesity  teen_crime  tuberculosis  \
0             NaN           79.3       NaN      NaN         NaN           NaN   
1             NaN            NaN       NaN      NaN         NaN        2875.0   
2             NaN            NaN       NaN      NaN         NaN        2345.0   
3             NaN           84.5       NaN      NaN         NaN        2251.0   
4             NaN            NaN       NaN      NaN         NaN        2217.0   
5             NaN            NaN       NaN      NaN         NaN        2258.0   
6             5.1           79.6       NaN      5.9         NaN        2537.0   
7             5.2            NaN       NaN      5.3         NaN        2611.0   
8             5.1            NaN       NaN      5.3       18.03        2256.0   
9             5.1           80.0       NaN      5.1       17.33        2421.0   
10            5.3            NaN     148.0      5.3       13.90        2338.0   
11            4.9            NaN     143.0      5.6       12.97        2335.0   
12            4.3           77.1     129.0      6.2       16.60        1829.0   
13            5.3            NaN     126.0      6.6       14.56        1436.0   
14            5.3            NaN      95.0      6.9       13.16        1246.0   
15            5.0           79.6      83.0      7.5       14.05        1142.0   
16            4.6            NaN      68.0      9.1       13.93         852.0   
17            5.2            NaN      57.0     10.0       13.72         697.0   
18            5.7           82.3      45.0     10.8       12.91         474.0   

    pre_puberty  single  private_edu  exercise3_week  \
0           NaN     NaN          NaN             NaN   
1           NaN     NaN          NaN             NaN   
2           NaN     NaN          NaN             NaN   
3           NaN     NaN          NaN             NaN   
4           NaN     NaN          NaN             NaN   
5           NaN     8.6          NaN            32.5   
6           NaN     8.8          NaN            31.9   
7           NaN     8.9         77.0            29.9   
8           NaN     9.0         75.1            31.8   
9           NaN     9.1         75.0            31.6   
10     0.413820     9.2         73.6            33.0   
11     0.692249     9.3         71.7            34.1   
12     0.858238     9.9         69.4            33.6  

In [5]:
# KNN으로 결측치 처리하기
welfac = pr['welfare_fac']
welfac = pd.DataFrame(welfac)

# import knnimpute
from missingpy import KNNImputer
imputer = KNNImputer(n_neighbors=2)
welfac_new = imputer.fit_transform(welfac)
welfac_new

C:\Users\ICT01_04\Anaconda3\lib\site-packages\missingpy\knnimpute.py:224: UserWarning: There are rows with more than 50.0% missing values. These rows are not included as donor neighbors.
  .format(self.row_max_missing * 100))
C:\Users\ICT01_04\Anaconda3\lib\site-packages\missingpy\knnimpute.py:282: UserWarning: There are rows with more than 50.0% missing values. The missing features in these rows are imputed with column means.
  .format(self.row_max_missing * 100))


array([[ 8.84666667],
       [ 8.84666667],
       [ 8.84666667],
       [ 2.24      ],
       [ 2.52      ],
       [ 3.21      ],
       [ 4.05      ],
       [ 4.81      ],
       [ 6.54      ],
       [ 8.37      ],
       [10.74      ],
       [11.01      ],
       [11.61      ],
       [12.42      ],
       [13.07      ],
       [13.56      ],
       [14.15      ],
       [14.4       ],
       [ 8.84666667]])

In [3]:
import nltk
import sklearn
# pip freeze | grep scikit-learn
print('The nltk version is {}.'.format(nltk.__version__))
print('The scikit-learn version is {}.'.format(sklearn.__version__)) 

The nltk version is 3.4.5.
The scikit-learn version is 0.22.1.


In [4]:
import numpy as np
from missingpy import KNNImputer
nan = np.nan
X = [[1, 2, nan], [3, 4, 3], [nan, 6, 5], [8, 8, 7]]
imputer = KNNImputer(n_neighbors=2, weights="uniform")
imputer.fit_transform(X)


C:\Users\ICT01_04\Anaconda3\lib\site-packages\missingpy\pairwise_external.py:135: FutureWarning: 'warn_on_dtype' is deprecated in version 0.21 and will be removed in 0.23. Don't set `warn_on_dtype` to remove this warning.
  warn_on_dtype=warn_on_dtype, estimator=estimator)
C:\Users\ICT01_04\Anaconda3\lib\site-packages\missingpy\pairwise_external.py:138: FutureWarning: 'warn_on_dtype' is deprecated in version 0.21 and will be removed in 0.23. Don't set `warn_on_dtype` to remove this warning.
  warn_on_dtype=warn_on_dtype, estimator=estimator)


array([[1. , 2. , 4. ],
       [3. , 4. , 3. ],
       [5.5, 6. , 5. ],
       [8. , 8. , 7. ]])